# Generated by Django 3.2.2 on 2021-05-14 06:35

import _socket
from django.db import migrations, models
import django.db.models.deletion
import django_crypto_fields.fields.firstname_field
import django_crypto_fields.fields.identity_field
import django_crypto_fields.fields.lastname_field
import django_revision.revision_field
import edc_base.model_fields.date_estimated
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.model_validators.date
import edc_base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('vaccine_subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eligibilitychecklist',
            options={'verbose_name': 'EligibilityCheckList', 'verbose_name_plural': 'EligibilityCheckList'},
        ),
        migrations.AlterField(
            model_name='eligibilitychecklist',
            name='age_in_years',
            field=models.IntegerField(help_text='(Years)', verbose_name='What is the participants age?'),
        ),
        migrations.CreateModel(
            name='InformedConsent',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('consent_datetime', models.DateTimeField(default=edc_base.utils.get_utcnow, help_text='Date and time of consent.', verbose_name='Consent datetime')),
                ('clinician_names', models.CharField(max_length=50, verbose_name='Clinician names')),
                ('first_name', django_crypto_fields.fields.firstname_field.FirstnameField(blank=True, help_text=' (Encryption: RSA local)', max_length=71)),
                ('last_name', django_crypto_fields.fields.lastname_field.LastnameField(blank=True, help_text=' (Encryption: RSA local)', max_length=71)),
                ('language', models.CharField(blank=True, choices=[('tn', 'Setswana'), ('en', 'English'), ('kck', 'Ikalanga')], help_text='The language used for the consent process will also be used during data collection.', max_length=50, null=True, verbose_name='Language of consent')),
                ('is_participant_literate', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='If No provide witness name on this form and signatureon the paper document', max_length=5, verbose_name='Is the participant literate?')),
                ('witness_last_and_first_name', models.CharField(max_length=5, verbose_name='Witness last and first name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('date_of_birth', models.DateField(validators=[edc_base.model_validators.date.date_not_future], verbose_name='Date of birth')),
                ('is_dob_estimated', edc_base.model_fields.date_estimated.IsDateEstimatedField(choices=[('-', 'No'), ('D', 'Yes, estimated the Day'), ('MD', 'Yes, estimated Month and Day'), ('YMD', 'Yes, estimated Year, Month and Day')], help_text='If the exact date is not known, please indicate which part of the date is estimated.', max_length=25, null=True, verbose_name='Is date of birth estimated?')),
                ('national_identity', django_crypto_fields.fields.identity_field.IdentityField(help_text=' (Encryption: RSA local)', max_length=71, unique=True, verbose_name='Patient ID number (Omang)')),
                ('identity_type', models.CharField(choices=[('country_id', 'Country ID number'), ('country_id_rcpt', 'Country ID receipt'), ('passport', 'Passport'), ('OTHER', 'Other')], max_length=25, verbose_name='What type of identity number is this?')),
                ('reviewed_consent', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='If no, participant is not eligible.', max_length=3, verbose_name='I have reviewed the consent with the participant')),
                ('answered_all_questions', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='If no, participant is not eligible.', max_length=3, verbose_name='I have answered all questions the participant had about the study')),
                ('asked_questions', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='If no, participant is not eligible.', max_length=3, verbose_name='I have asked the participant questions about this study and the participant has demonstrated understanding')),
                ('have_verified', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='If no, participant is not eligible.', max_length=3, verbose_name='I have verified that the participant hassigned the consent form')),
                ('copy_of_consent', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='if declined, return copy with the consent', max_length=3, verbose_name='I have provided the participant with a copy of their signed informed consent')),
                ('site', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
