# Generated by Django 3.2.2 on 2021-05-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_subject', '0002_auto_20210514_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informedconsent',
            old_name='is_dob_estimated',
            new_name='is_estimated',
        ),
        migrations.RenameField(
            model_name='informedconsent',
            old_name='is_participant_literate',
            new_name='is_literate',
        ),
        migrations.RemoveField(
            model_name='eligibilitychecklist',
            name='clinician_names',
        ),
        migrations.RemoveField(
            model_name='eligibilitychecklist',
            name='participant_identifier',
        ),
        migrations.RemoveField(
            model_name='informedconsent',
            name='clinician_names',
        ),
        migrations.AlterField(
            model_name='eligibilitychecklist',
            name='subject_identifier',
            field=models.CharField(max_length=36, unique=True, verbose_name='Participant ID'),
        ),
    ]
