# Generated by Django 3.2.2 on 2021-05-14 07:33

from django.db import migrations, models
import django_crypto_fields.fields.firstname_field
import django_crypto_fields.fields.lastname_field


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_subject', '0003_auto_20210514_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informedconsent',
            name='witness_last_and_first_name',
        ),
        migrations.AddField(
            model_name='informedconsent',
            name='witness_fname',
            field=django_crypto_fields.fields.firstname_field.FirstnameField(blank=True, help_text=' (Encryption: RSA local)', max_length=71, verbose_name='Witness first name'),
        ),
        migrations.AddField(
            model_name='informedconsent',
            name='witness_lname',
            field=django_crypto_fields.fields.lastname_field.LastnameField(blank=True, help_text=' (Encryption: RSA local)', max_length=71, verbose_name='Witness last name'),
        ),
        migrations.AlterField(
            model_name='eligibilitychecklist',
            name='subject_identifier',
            field=models.CharField(max_length=36, unique=True, verbose_name='Subject ID'),
        ),
    ]
