# Generated by Django 3.2.2 on 2021-05-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_subject', '0005_subjectlocator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectlocator',
            options={'verbose_name': 'Subject Locator', 'verbose_name_plural': 'Subject Locator'},
        ),
    ]
